// Fragenpool IT-Sicherheit (I1–I5)
[
  // ---------------------------------------------------------------- I1
  { id: "I1-01", modul: "I1", typ: "mc", niveau: 1, frage: "Eine **USV** schützt vor allem welches Schutzziel?", optionen: ["Vertraulichkeit", "Integrität", "Verfügbarkeit", "Authentizität"], richtig: 2,
    erklaerung: "Die USV hält Systeme bei Stromausfall am Laufen → **Verfügbarkeit**." },
  { id: "I1-02", modul: "I1", typ: "mc", niveau: 1, frage: "Ein Angreifer ändert unbemerkt die IBAN in einer Rechnung. Welches Schutzziel ist verletzt?", optionen: ["Vertraulichkeit", "Integrität", "Verfügbarkeit", "keines"], richtig: 1,
    erklaerung: "Die Daten wurden **unbefugt verändert** → Integrität." },
  { id: "I1-03", modul: "I1", typ: "mc", niveau: 2, frage: "Nach dem **Maximumprinzip** erhält ein Server …", optionen: ["den Durchschnitt des Schutzbedarfs seiner Anwendungen", "je Schutzziel den höchsten Schutzbedarf der darauf laufenden Anwendungen", "immer „sehr hoch“", "den niedrigsten Schutzbedarf"], richtig: 1,
    erklaerung: "Der Server ist so schutzbedürftig wie seine kritischste Anwendung – für jedes Schutzziel einzeln." },
  { id: "I1-04", modul: "I1", typ: "mc", niveau: 2, frage: "Was beschreibt der **Kumulationseffekt**?", optionen: ["Viele Anwendungen mit normalem Schutzbedarf auf einem System können zusammen einen höheren Schutzbedarf ergeben", "Schutzbedarf sinkt durch Redundanz", "Mehrere Schutzziele werden zu einem zusammengefasst", "Risiken heben sich gegenseitig auf"], richtig: 0,
    erklaerung: "Fällt ein Host mit vielen „normalen“ Diensten aus, ist der Gesamtschaden beträchtlich." },
  { id: "I1-05", modul: "I1", typ: "mc", niveau: 2, frage: "Was bedeutet **SOLLTE** in einer Anforderung des IT-Grundschutz-Kompendiums?", optionen: ["Die Anforderung ist optional", "Die Anforderung ist normalerweise umzusetzen; Abweichen nur mit stichhaltiger, dokumentierter Begründung", "Die Anforderung ist gesetzlich verpflichtend", "Die Anforderung gilt nur für Behörden"], richtig: 1,
    erklaerung: "MUSS = unbedingt, SOLLTE = Regelfall mit begründeter Ausnahme." },
  { id: "I1-06", modul: "I1", typ: "multi", niveau: 2, frage: "Welche Maßnahmen sind **organisatorisch**?", optionen: ["Vier-Augen-Prinzip bei Überweisungen", "Firewall", "Passwortrichtlinie", "Vertretungsregelung", "Brandmeldeanlage"], richtig: [0, 2, 3],
    erklaerung: "Firewall = technisch, Brandmeldeanlage = infrastrukturell." },
  { id: "I1-07", modul: "I1", typ: "mc", niveau: 1, frage: "Wie wird ein **Risiko** üblicherweise bewertet?", optionen: ["Kosten der Maßnahme × Anzahl Systeme", "Eintrittswahrscheinlichkeit × Schadenshöhe", "Anzahl Bedrohungen + Schwachstellen", "Schutzbedarf − Maßnahmen"], richtig: 1,
    erklaerung: "Risiko = **Wahrscheinlichkeit × Auswirkung**." },
  { id: "I1-08", modul: "I1", typ: "mc", niveau: 2, frage: "Die geheime Konstruktionszeichnung eines Produkts soll geschützt werden. Welcher Bereich ist zuständig?", optionen: ["nur Datenschutz", "Informationssicherheit", "Arbeitsschutz", "keiner"], richtig: 1,
    erklaerung: "Datenschutz schützt **Personen**. Betriebsgeheimnisse fallen unter die **Informationssicherheit**." },
  { id: "I1-09", modul: "I1", typ: "mc", niveau: 2, frage: "Welcher BSI-Standard beschreibt die **IT-Grundschutz-Methodik**?", optionen: ["200-1", "200-2", "200-3", "200-4"], richtig: 1,
    erklaerung: "200-1 ISMS · **200-2 IT-Grundschutz-Methodik** · 200-3 Risikoanalyse · 200-4 Business Continuity Management." },
  { id: "I1-10", modul: "I1", typ: "mc", niveau: 1, frage: "Welches Schutzziel stellt sicher, dass eine Nachricht **wirklich vom angegebenen Absender** stammt?", optionen: ["Verfügbarkeit", "Authentizität", "Vertraulichkeit", "Belastbarkeit"], richtig: 1,
    erklaerung: "**Authentizität** – Echtheit des Absenders bzw. der Daten (z. B. per digitaler Signatur)." },

  // ---------------------------------------------------------------- I2
  { id: "I2-01", modul: "I2", typ: "multi", niveau: 1, frage: "Welche Daten sind **personenbezogen**?", optionen: ["IP-Adresse eines Kunden", "Jahresumsatz einer GmbH", "Personalnummer", "anonymisierte Besucherstatistik", "Foto eines Mitarbeiters"], richtig: [0, 2, 4],
    erklaerung: "Personenbezogen = eine natürliche Person ist identifizierbar. GmbH-Umsatz und echte Anonymisierung sind es nicht." },
  { id: "I2-02", modul: "I2", typ: "zahl", niveau: 1, frage: "Innerhalb wie vieler **Stunden** muss eine meldepflichtige Datenpanne der Aufsichtsbehörde gemeldet werden?", richtig: 72, toleranz: 0, einheit: "h",
    erklaerung: "Art. 33 DSGVO: unverzüglich, möglichst **binnen 72 Stunden** nach Bekanntwerden." },
  { id: "I2-03", modul: "I2", typ: "mc", niveau: 1, frage: "Chipkarte an der Tür zum Serverraum – welche Kontrollart?", optionen: ["Zutrittskontrolle", "Zugangskontrolle", "Zugriffskontrolle", "Eingabekontrolle"], richtig: 0,
    erklaerung: "**Zutritt** = Räume. Zugang = Systeme, Zugriff = Daten." },
  { id: "I2-04", modul: "I2", typ: "mc", niveau: 1, frage: "Kontosperre nach fünf falschen Passworteingaben – welche Kontrollart?", optionen: ["Zutrittskontrolle", "Zugangskontrolle", "Zugriffskontrolle", "Weitergabekontrolle"], richtig: 1,
    erklaerung: "Schutz der **Anmeldung am System** → Zugangskontrolle." },
  { id: "I2-05", modul: "I2", typ: "mc", niveau: 2, frage: "Jede Änderung im Kundenstamm wird mit Benutzer und Zeitstempel protokolliert. Welche Kontrollart?", optionen: ["Zugriffskontrolle", "Eingabekontrolle", "Verfügbarkeitskontrolle", "Trennungsgebot"], richtig: 1,
    erklaerung: "**Eingabekontrolle**: nachvollziehen, wer was wann eingegeben/geändert hat." },
  { id: "I2-06", modul: "I2", typ: "mc", niveau: 2, frage: "Was ist bei der Nutzung eines externen **Cloud-Dienstleisters** für Kundendaten zwingend nötig?", optionen: ["Eine Einwilligung jedes Kunden", "Ein Auftragsverarbeitungsvertrag (AVV) nach Art. 28 DSGVO", "Eine Genehmigung der Polizei", "Nichts, wenn der Anbieter bekannt ist"], richtig: 1,
    erklaerung: "Der Cloud-Anbieter ist **Auftragsverarbeiter** → AVV." },
  { id: "I2-07", modul: "I2", typ: "mc", niveau: 2, frage: "Welche Aussage zu **pseudonymisierten** Daten stimmt?", optionen: ["Sie fallen nicht mehr unter die DSGVO", "Sie bleiben personenbezogen, weil mit Zusatzwissen ein Bezug herstellbar ist", "Sie sind identisch mit anonymisierten Daten", "Sie dürfen ohne Rechtsgrundlage verarbeitet werden"], richtig: 1,
    erklaerung: "Nur **Anonymisierung** entfernt den Personenbezug dauerhaft." },
  { id: "I2-08", modul: "I2", typ: "multi", niveau: 2, frage: "Welche gehören zu den **Grundsätzen** nach Art. 5 DSGVO?", optionen: ["Zweckbindung", "Datenminimierung", "Speicherbegrenzung", "Gewinnmaximierung", "Rechenschaftspflicht"], richtig: [0, 1, 2, 4],
    erklaerung: "Außerdem: Rechtmäßigkeit/Transparenz, Richtigkeit, Integrität und Vertraulichkeit." },
  { id: "I2-09", modul: "I2", typ: "zahl", niveau: 2, frage: "Ab wie vielen Personen, die ständig mit der automatisierten Verarbeitung personenbezogener Daten beschäftigt sind, muss in Deutschland i. d. R. ein Datenschutzbeauftragter benannt werden?", richtig: 20, toleranz: 0,
    erklaerung: "§ 38 BDSG: in der Regel ab **20** Personen." },
  { id: "I2-10", modul: "I2", typ: "mc", niveau: 2, frage: "Die Lieferadresse eines Onlinekunden wird verarbeitet. Welche Rechtsgrundlage greift?", optionen: ["Einwilligung", "Erfüllung eines Vertrags", "lebenswichtiges Interesse", "öffentliche Aufgabe"], richtig: 1,
    erklaerung: "Ohne Adresse kann die Bestellung nicht geliefert werden → Art. 6 Abs. 1 **lit. b** (Vertrag)." },
  { id: "I2-11", modul: "I2", typ: "mc", niveau: 1, frage: "Welche Daten gehören zu den **besonderen Kategorien** nach Art. 9 DSGVO?", optionen: ["E-Mail-Adresse", "Gesundheitsdaten", "Kundennummer", "Geburtsdatum"], richtig: 1,
    erklaerung: "Gesundheit, Religion, ethnische Herkunft, politische Meinung, Biometrie u. a. sind besonders geschützt." },
  { id: "I2-12", modul: "I2", typ: "mc", niveau: 2, frage: "Lohndaten werden nur verschlüsselt an das Steuerbüro übertragen. Welche Kontrollart?", optionen: ["Weitergabekontrolle", "Auftragskontrolle", "Zugangskontrolle", "Trennungsgebot"], richtig: 0,
    erklaerung: "Schutz bei **Übertragung/Transport** → Weitergabekontrolle." },

  // ---------------------------------------------------------------- I3
  { id: "I3-01", modul: "I3", typ: "mc", niveau: 1, frage: "Was sichert eine **inkrementelle** Sicherung?", optionen: ["alle Daten", "alle Änderungen seit der letzten Vollsicherung", "alle Änderungen seit der letzten Sicherung (egal welcher Art)", "nur Systemdateien"], richtig: 2,
    erklaerung: "Inkrementell = seit der **letzten Sicherung**. Differenziell = seit der letzten **Vollsicherung**." },
  { id: "I3-02", modul: "I3", typ: "mc", niveau: 2, frage: "Mo Voll, Di–Do **differenziell**. Ausfall nach der Sicherung am Donnerstag. Was wird zur Wiederherstellung benötigt?", optionen: ["nur Do", "Mo + Di + Mi + Do", "Mo + Do", "Mo + Mi"], richtig: 2,
    erklaerung: "Die letzte differenzielle Sicherung enthält alle Änderungen seit Montag → **Voll + letzte Differenzielle**." },
  { id: "I3-03", modul: "I3", typ: "zahl", niveau: 2, frage: "Vollsicherung 500 GB, danach 4 **differenzielle** Sicherungen, täglich ändern sich 20 GB (immer andere Daten). Speicherbedarf aller Sicherungen in GB?", richtig: 700, toleranz: 0, einheit: "GB",
    erklaerung: "500 + 20 + 40 + 60 + 80 = **700 GB** (inkrementell wären es 500 + 4 × 20 = 580 GB)." },
  { id: "I3-04", modul: "I3", typ: "text", niveau: 1, frage: "Wie heißt die Regel „3 Kopien, 2 Medien, 1 Kopie außer Haus“? (Zahlenfolge)", richtig: ["3-2-1", "321", "3 2 1", "3-2-1-Regel"],
    erklaerung: "**3-2-1-Regel**, erweitert 3-2-1-1-0 (1 offline/unveränderbar, 0 Fehler beim Restore-Test)." },
  { id: "I3-05", modul: "I3", typ: "mc", niveau: 2, frage: "Was gibt der **RPO** an?", optionen: ["die maximale Ausfallzeit", "den maximal tolerierbaren Datenverlust (Zeitraum)", "die Anzahl der Backupmedien", "die Aufbewahrungsdauer"], richtig: 1,
    erklaerung: "RPO bestimmt die **Sicherungshäufigkeit**; RTO ist die maximale Ausfallzeit bis zur Wiederherstellung." },
  { id: "I3-06", modul: "I3", typ: "multi", niveau: 2, frage: "Was ist **kein** vollwertiger Ersatz für ein Backup?", optionen: ["RAID 1", "Echtzeit-Spiegelung auf einen zweiten Server", "Snapshot auf demselben Speicher", "Offline-Sicherung auf Band im Tresor eines anderen Gebäudes"], richtig: [0, 1, 2],
    erklaerung: "RAID, Spiegelung und Snapshots übernehmen Löschungen/Verschlüsselungen bzw. liegen auf demselben System." },
  { id: "I3-07", modul: "I3", typ: "mc", niveau: 2, frage: "Welches Backupmedium ist besonders **günstig pro TB** und lässt sich leicht **offline** lagern?", optionen: ["NVMe-SSD", "LTO-Band", "RAM-Disk", "NAS im gleichen Raum"], richtig: 1,
    erklaerung: "**LTO-Bänder**: günstig, langlebig, offline (Air Gap) – gut gegen Ransomware." },
  { id: "I3-08", modul: "I3", typ: "mc", niveau: 1, frage: "Warum müssen Backups regelmäßig **testweise zurückgespielt** werden?", optionen: ["Damit die Bänder nicht verstauben", "Weil nur ein erfolgreicher Restore beweist, dass die Sicherung vollständig und nutzbar ist", "Das ist gesetzlich nur für Banken nötig", "Um Speicherplatz zu sparen"], richtig: 1,
    erklaerung: "Fehlerhafte oder unvollständige Sicherungen fallen sonst erst im Ernstfall auf." },
  { id: "I3-09", modul: "I3", typ: "mc", niveau: 2, frage: "Was ist das **Generationenprinzip** (Großvater–Vater–Sohn)?", optionen: ["Sicherung auf drei Festplatten gleichzeitig", "Rotierende tägliche, wöchentliche und monatliche Sicherungen, damit mehrere ältere Stände verfügbar sind", "Nur die letzten drei Sicherungen behalten", "Sicherung durch drei Personen"], richtig: 1,
    erklaerung: "Sohn = täglich, Vater = wöchentlich, Großvater = monatlich." },
  { id: "I3-10", modul: "I3", typ: "mc", niveau: 3, frage: "Welcher Nachteil hat die **inkrementelle** Sicherung gegenüber der differenziellen?", optionen: ["Sie braucht mehr Speicher", "Die Wiederherstellung braucht alle Inkremente – fehlt eines, sind alle späteren wertlos", "Sie dauert länger bei der Sicherung", "Sie kann keine Datenbanken sichern"], richtig: 1,
    erklaerung: "Inkrementell spart Speicher/Zeit beim Sichern, ist aber beim Restore aufwendiger und empfindlicher." },

  // ---------------------------------------------------------------- I4
  { id: "I4-01", modul: "I4", typ: "mc", niveau: 1, frage: "Mit welchem Schlüssel verschlüsselt Anna eine Nachricht, die **nur Ben** lesen können soll?", optionen: ["Annas privatem Schlüssel", "Annas öffentlichem Schlüssel", "Bens öffentlichem Schlüssel", "Bens privatem Schlüssel"], richtig: 2,
    erklaerung: "Verschlüsseln mit dem **öffentlichen Schlüssel des Empfängers** – nur dessen privater Schlüssel entschlüsselt." },
  { id: "I4-02", modul: "I4", typ: "mc", niveau: 1, frage: "Mit welchem Schlüssel erstellt Anna eine **digitale Signatur**?", optionen: ["Annas privatem Schlüssel", "Annas öffentlichem Schlüssel", "Bens öffentlichem Schlüssel", "einem gemeinsamen symmetrischen Schlüssel"], richtig: 0,
    erklaerung: "Signieren mit dem **eigenen privaten** Schlüssel, prüfen mit dem öffentlichen." },
  { id: "I4-03", modul: "I4", typ: "zahl", niveau: 2, frage: "Wie viele **symmetrische** Schlüssel braucht man, damit 12 Personen paarweise geheim kommunizieren können?", richtig: 66, toleranz: 0,
    erklaerung: "n · (n − 1) / 2 = 12 · 11 / 2 = **66**." },
  { id: "I4-04", modul: "I4", typ: "mc", niveau: 2, frage: "Warum nutzt TLS ein **hybrides** Verfahren?", optionen: ["Weil symmetrische Verfahren unsicher sind", "Asymmetrisch für den sicheren Schlüsselaustausch, symmetrisch für die schnelle Datenübertragung", "Weil Browser keine asymmetrischen Verfahren kennen", "Aus Lizenzgründen"], richtig: 1,
    erklaerung: "Kombiniert die Stärken: kein Geheimnis vorab nötig **und** hohe Geschwindigkeit." },
  { id: "I4-05", modul: "I4", typ: "multi", niveau: 2, frage: "Welche Eigenschaften hat eine kryptografische **Hashfunktion**?", optionen: ["Einwegfunktion (nicht umkehrbar)", "Ausgabe hat feste Länge", "kleine Änderung → völlig anderer Hash", "mit dem richtigen Schlüssel entschlüsselbar"], richtig: [0, 1, 2],
    erklaerung: "Hashes haben keinen Schlüssel und lassen sich nicht zurückrechnen." },
  { id: "I4-06", modul: "I4", typ: "mc", niveau: 1, frage: "Welches Hashverfahren gilt heute als **sicher**?", optionen: ["MD5", "SHA-1", "SHA-256", "CRC32"], richtig: 2,
    erklaerung: "**SHA-256** (SHA-2) oder SHA-3. MD5 und SHA-1 sind gebrochen, CRC32 ist nur eine Prüfsumme." },
  { id: "I4-07", modul: "I4", typ: "mc", niveau: 2, frage: "Welche Schutzziele stellt eine digitale Signatur sicher?", optionen: ["nur Vertraulichkeit", "Integrität, Authentizität und Nichtabstreitbarkeit", "Verfügbarkeit", "Vertraulichkeit und Verfügbarkeit"], richtig: 1,
    erklaerung: "Die Signatur verschlüsselt den Inhalt **nicht** – Vertraulichkeit braucht zusätzliche Verschlüsselung." },
  { id: "I4-08", modul: "I4", typ: "mc", niveau: 2, frage: "Was bestätigt ein **digitales Zertifikat**?", optionen: ["dass ein Passwort sicher ist", "dass ein öffentlicher Schlüssel zu einer bestimmten Identität gehört", "dass eine Datei virenfrei ist", "dass eine Webseite schnell lädt"], richtig: 1,
    erklaerung: "Die **CA** bestätigt mit ihrer Signatur die Zuordnung Public Key ↔ Person/Domain (X.509)." },
  { id: "I4-09", modul: "I4", typ: "mc", niveau: 2, frage: "Wozu dient ein **Salt** beim Speichern von Passwort-Hashes?", optionen: ["Er verschlüsselt das Passwort", "Er sorgt dafür, dass gleiche Passwörter unterschiedliche Hashes erhalten und vorberechnete Tabellen nutzlos werden", "Er beschleunigt die Anmeldung", "Er ersetzt die Hashfunktion"], richtig: 1,
    erklaerung: "Salt = Zufallswert je Benutzer → schützt vor Rainbow-Tables." },
  { id: "I4-10", modul: "I4", typ: "mc", niveau: 1, frage: "Welches Verfahren ist **symmetrisch**?", optionen: ["RSA", "AES", "ECC", "Diffie-Hellman"], richtig: 1,
    erklaerung: "**AES** ist symmetrisch; RSA und ECC sind asymmetrisch, Diffie-Hellman dient der Schlüsselvereinbarung." },
  { id: "I4-11", modul: "I4", typ: "mc", niveau: 2, frage: "Ein Notebook soll gegen Datendiebstahl bei Verlust geschützt werden. Welche Lösung passt?", optionen: ["S/MIME", "Festplattenverschlüsselung, z. B. BitLocker mit TPM", "HTTPS", "Hashen aller Dateien"], richtig: 1,
    erklaerung: "Daten „at rest“ → **Festplattenverschlüsselung** (symmetrisch, AES)." },

  // ---------------------------------------------------------------- I5
  { id: "I5-01", modul: "I5", typ: "mc", niveau: 1, frage: "Welche Schadsoftware verbreitet sich **selbstständig** über Netzwerke?", optionen: ["Virus", "Wurm", "Trojaner", "Adware"], richtig: 1,
    erklaerung: "Ein **Wurm** braucht keinen Wirt und keine Nutzeraktion. Ein Virus hängt an einer Datei, die ausgeführt werden muss." },
  { id: "I5-02", modul: "I5", typ: "mc", niveau: 1, frage: "Ein Programm tarnt sich als nützliches Tool, öffnet aber heimlich eine Hintertür. Was ist das?", optionen: ["Wurm", "Trojaner", "Rootkit", "Scareware"], richtig: 1,
    erklaerung: "**Trojaner** (Trojanisches Pferd)." },
  { id: "I5-03", modul: "I5", typ: "multi", niveau: 2, frage: "Welche Kombinationen sind echte **Zwei-Faktor-Authentifizierung**?", optionen: ["Passwort + Code aus Authenticator-App", "Passwort + Sicherheitsfrage", "Chipkarte + PIN", "Fingerabdruck + Passwort", "zwei verschiedene Passwörter"], richtig: [0, 2, 3],
    erklaerung: "Die Faktoren müssen aus **verschiedenen Kategorien** stammen (Wissen, Besitz, Sein)." },
  { id: "I5-04", modul: "I5", typ: "mc", niveau: 1, frage: "Ein Mitarbeiter bemerkt, dass seine Dateien verschlüsselt werden. Was tut er **zuerst**?", optionen: ["PC ausschalten", "Gerät vom Netzwerk trennen und sofort die IT informieren", "Lösegeld zahlen", "Dateien in die Cloud kopieren"], richtig: 1,
    erklaerung: "Netzwerk trennen verhindert die Ausbreitung; Ausschalten würde Spuren vernichten." },
  { id: "I5-05", modul: "I5", typ: "mc", niveau: 2, frage: "Was ist **Credential Stuffing**?", optionen: ["Passwörter zufällig durchprobieren", "Geleakte Benutzername-Passwort-Kombinationen bei anderen Diensten ausprobieren", "Zugangsdaten auf Zettel schreiben", "Ein Angriff auf WLAN-Router"], richtig: 1,
    erklaerung: "Funktioniert, weil viele Menschen Passwörter wiederverwenden → einzigartige Passwörter + MFA." },
  { id: "I5-06", modul: "I5", typ: "mc", niveau: 2, frage: "Die Buchhaltung erhält eine Mail „vom Chef“: sofort 48 000 € für eine geheime Übernahme überweisen. Welcher Angriff ist das, und was hilft?", optionen: ["DDoS – Firewall", "CEO-Fraud – Rückruf über bekannte Nummer und Vier-Augen-Prinzip", "SQL-Injection – Prepared Statements", "Wurm – Virenscanner"], richtig: 1,
    erklaerung: "**CEO-Fraud** nutzt Autorität und Zeitdruck. Feste Freigabeprozesse und Rückruf verhindern Schaden." },
  { id: "I5-07", modul: "I5", typ: "mc", niveau: 2, frage: "Welche Maßnahme schützt eine Webanwendung vor **SQL-Injection**?", optionen: ["Längere Passwörter", "Prepared Statements / parametrisierte Abfragen", "Mehr RAM", "HTTPS"], richtig: 1,
    erklaerung: "Eingaben werden nie als SQL-Code interpretiert. HTTPS verschlüsselt nur den Transport." },
  { id: "I5-08", modul: "I5", typ: "mc", niveau: 2, frage: "Was unterscheidet eine **Stateful-Inspection-Firewall** von einem einfachen Paketfilter?", optionen: ["Sie prüft auch den Verbindungszustand und lässt Antworten auf erlaubte Verbindungen automatisch zu", "Sie arbeitet nur auf Schicht 1", "Sie verschlüsselt Daten", "Sie ersetzt den Virenscanner"], richtig: 0,
    erklaerung: "Stateful Firewalls merken sich Verbindungen (Zustandstabelle)." },
  { id: "I5-09", modul: "I5", typ: "multi", niveau: 2, frage: "Woran erkennt man typischerweise eine **Phishing-Mail**?", optionen: ["Zeitdruck oder Drohung", "Absenderdomain passt nicht zum angeblichen Absender", "Link führt auf eine fremde Domain", "Die Mail kommt von einer bekannten internen Adresse und enthält keine Aufforderung"], richtig: [0, 1, 2],
    erklaerung: "Druck, gefälschte Absender und fremde Linkziele sind typische Merkmale." },
  { id: "I5-10", modul: "I5", typ: "mc", niveau: 2, frage: "Was empfiehlt das BSI heute für Passwörter?", optionen: ["Monatlicher Pflichtwechsel", "Lange, einzigartige Passwörter bzw. Passphrasen, Passwortmanager, Wechsel bei Verdacht", "Genau 8 Zeichen mit Sonderzeichen", "Dasselbe starke Passwort überall"], richtig: 1,
    erklaerung: "**Länge** und **Einzigartigkeit** zählen; erzwungene Wechsel ohne Anlass führen zu schwachen Mustern." },
  { id: "I5-11", modul: "I5", typ: "zahl", niveau: 3, frage: "Wie viele Kombinationen hat eine **4-stellige PIN** aus Ziffern?", richtig: 10000, toleranz: 0,
    erklaerung: "10⁴ = **10 000** – deshalb sind PINs nur mit Fehlversuchssperre sicher." },
]
